### ISSUE TITLE
Suggestion: Change versionName

### ISSUE THREAD

**Issue by tonyp** [rovo89/XposedInstaller#284]
I think it would make sense to remove the "alpha 2" part from the version name and rather use an own naming scheme (3.1 etc). It seems to confuse lots of people who flashed alpha4 but still see alpha2 in the installer.

And while I'm at it: It might be a good idea to change the "installation_lollipop" string somehow - many people confuse it with an error message (as that's the place and color the Installer uses for errors). Maybe just hide it when Xposed has been flashed successfully?

**Comment by pylerSM** [comment]
Yes, definitely a good idea. But even if you do it, there is no activity here or maybe your PR will be closed w/o any reason. There are many useful patches here as pull requests and they were not merged atleast to Xposed Installer for Lollipop. (Pre Lollipop hadly will get these features sadly.. they can use only my mod version based on 2.7 experimental 1 with patches from here + my own, which rovo89 doesn't like, but many people wants them and me too!)

Anyway, if you want, try to fix it and send PR. Since java part of Xposed Installer is not so hard, rovo89 could make you or other coders and official contributors.

I fully understand there is a lot of work with Xposed low level stuffs and rovo89 has not as much time as he had so why not help him better way. He & new guys could fix Xposed internals and some other people can focus on UI. But please not in the way of milion of forks, unofficial builds. Really bad for people to get the right build, right APK. Some of them possibly killed their phones just because of it.

**Comment by tonyp** [comment]
@pylerSM: personally I can't complain about how the issues and pull requests get handled, so far everything I was involved with got addressed in a fair manner.
Creating a PR won't be a problem, but I don't just want to throw out an uncommented feature. I'm sure rovo will consider a couple issues and pull requests when he decides it's time for another installer release - and I leave that judgement to him. I take the fact that this PR is still open as an assurance that it will be considered in due time.

Of course I can understand your frustration when pull requests get closed without any comment, but this is hardly the right place to discuss it (maybe ask in the closed one? So far rovo has always been very responsive in why something doesn't fit).
Yes, certainly a couple more contributors wouldn't harm, but they have to be fully aware of the scale and impact this project has. I didn't closely follow all the pull requests of this repo, but I remember some which just change a couple lines of code without any explanation, translation requests with XML issues and bare commits labeled as "untested but should work". That obviously can be a bit frustrating and hard to maintain.
I believe that especially deeper changes should be well tested before added as a pull request and contain a proper commit message.
The installer doesn't have to be pretty or filled with features, it has to be a reliable companion, so stability goes beyond everything else.

**Comment by pylerSM** [comment]
I tested my features in my build - mod version. They are okay. But I lost interest to improve my PRs because I see no reason to improve them since my work may never be actually used.

That closed PR was about disabling (showing) toasts when there is network failure during refresh. It should be logged to logcat, no as toasts.

But I accept owner's decision, it is his project.

**Comment by rovo89** [comment]
I've been thinking about version numbers a bit. Currently, there are several different versions:
- Xposed Installer (3.0 alpha2)
- app_process (61)
- XposedBridge.jar (64)
- the ZIPs I uploaded with app_process, XposedBridge.jar and modified ART runtime (3.0 alpha4 [20150430])

Following this pattern, the ART libraries and binaries would need their own version numbers as well.

But I think it would make sense to see the framework (consisting of app_process, XposedBridge.jar and ART runtime) as a unity that has a single version number, which would be stored in the /system/xposed.prop file that comes with the ZIP file. So app_process and XposedBridge.jar would have their version numbers remove to avoid confusion. In places where currently the version number of XposedBridge.jar is checked (installer, logs, `XposedBridge.XPOSED_BRIDGE_VERSION`), the logic would be changed to read the version from xposed.prop instead. And to avoid confusion between installer version and framework version, I would use integers for the ZIPs in the future (or strings that start with an integer, to allow for suffixes in custom builds). So the next one would probably be version 65 (instead of 3.0 alpha5).

Does that make sense?

**Comment by tonyp** [comment]
Yep this would certainly be an improvement. It does make sense for the files which are coupled to maintain a unique version number (at least externally). 

The Installer should keep an extra version scheme (which it already has, just the alpha2 part should get dropped or converted to e.g. 3.01a when you want to keep the alpha tag).

I don't really like the xposed.prop approach, though. You know how xda people are, some might mess with it and try to increase the version number (e.g. to install modules which require v64 but their phone only supports v54), so it might be better to keep this hidden rather than exposed in a publically accessible file. What do you think?

**Comment by rovo89** [comment]
> or converted to e.g. 3.01a

Any particular reason why you prefer this format over "3.0 alpha2"? For me, it looks more like a small hotfix or reupload for version 3.01... But I guess that's simply a matter of taste.

> You know how xda people are, some might mess with it and try to increase the version number (e.g. to install modules which require v64 but their phone only supports v54)

Well, if they want to try that, it's their own decision, and the risk is pretty limited. Besides the fact that those modules probably still won't work (because they required newer APIs), the only negative side-effect I see is that somebody who looks at the log file might make wrong assumptions due to the manipulated version number. If that becomes an issue, another idea I had (and even started to realize a while ago) might become handy:

I thought about adding checksums for the files added/replaced by Xposed to that xposed.prop file, mainly to ensure consistency. Not sure if it should (and could) prevent Xposed from loading, but it (app_process) could at least log any differences between the actual checksum and the one calculated at build time. It could also calculate a "total" of the checksums (e.g. by adding up the individual checksums, XOR'ing them or something like that) and compare it to the pre-calculated one. Obviously, this wouldn't prevent anyone from manipulating the version number. But if app_process logged the "total" checksum even in the positive case ("Installed files are consistent (checksum 1a2b3c4d)", one could compare the checksum of a posted logfile to the official one for that version and reject support in case it doesn't match.

Anyway, even without the checksum feature, I don't see a big risk as a consequence of a readable file, whereas compiling it into one of the files would require dummy changes (version bump only) to that binary, which is a bit nasty as well...

**Comment by tonyp** [comment]
> Any particular reason why you prefer this format over "3.0 alpha2"? For me, it looks more like a small hotfix or reupload for version 3.01... But I guess that's simply a matter of taste.

Actually I don't prefer 3.01 but think 3.0 alpha2 sounds better, I just thought about preventing confusion.
When you released "alpha 4" and the Installer still showed "alpha 2" it created (and still creates) a lot of confusion as people think flashing alpha 4 was unsuccessfull.
If you brand the next release as v65 without an additional "alpha x" tag you can certainly keep using the version scheme for the installer.
I just think there should be a clear way to distinguish the different releases (Xposed Installer vs the bundled "framework") to prevent confusion for less experienced users.

If you consider to introduce a new version scheme it might be worth to think about how to handle Android releases as well. I doubt it will happen, but in case there would come a bigger update to the pre-lollipop framework now it could create problems regarding the version numbers. Or an alpha for Android M gets released (by your or someone else) and Xposed for Lollipop still is in alpha status.
I didn't really think this part through, yet - just wanted to put it on the table.

**Comment by pylerSM** [comment]
To avoid current confusion, try to fix warning in Xposed Installer even if flash was successful and Xposed works. Improvment for alpha 5?

**Comment by rovo89** [comment]
I have realized this in installer version 3.0 alpha3 / framework version 65.
